// Code generated by "stringer -type=MMModemStateChangeReason"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemStateChangeReasonUnknown-0]
	_ = x[MmModemStateChangeReasonUserRequested-1]
	_ = x[MmModemStateChangeReasonSuspend-2]
	_ = x[MmModemStateChangeReasonFailure-3]
}

const _MMModemStateChangeReason_name = "MmModemStateChangeReasonUnknownMmModemStateChangeReasonUserRequestedMmModemStateChangeReasonSuspendMmModemStateChangeReasonFailure"

var _MMModemStateChangeReason_index = [...]uint8{0, 31, 68, 99, 130}

func (i MMModemStateChangeReason) String() string {
	if i >= MMModemStateChangeReason(len(_MMModemStateChangeReason_index)-1) {
		return "MMModemStateChangeReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemStateChangeReason_name[_MMModemStateChangeReason_index[i]:_MMModemStateChangeReason_index[i+1]]
}
