// Code generated by "stringer -type=MMModemStateFailedReason"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemPowerStateUnknown-0]
	_ = x[MmModemPowerStateOff-1]
	_ = x[MmModemPowerStateLow-2]
	_ = x[MmModemPowerStateOn-3]
}

const _MMModemStateFailedReason_name = "MmModemPowerStateUnknownMmModemPowerStateOffMmModemPowerStateLowMmModemPowerStateOn"

var _MMModemStateFailedReason_index = [...]uint8{0, 24, 44, 64, 83}

func (i MMModemStateFailedReason) String() string {
	if i >= MMModemStateFailedReason(len(_MMModemStateFailedReason_index)-1) {
		return "MMModemStateFailedReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemStateFailedReason_name[_MMModemStateFailedReason_index[i]:_MMModemStateFailedReason_index[i+1]]
}
