// Code generated by "stringer -type=MMModemState"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemStateFailed - -1]
	_ = x[MmModemStateUnknown-0]
	_ = x[MmModemStateInitializing-1]
	_ = x[MmModemStateLocked-2]
	_ = x[MmModemStateDisabled-3]
	_ = x[MmModemStateDisabling-4]
	_ = x[MmModemStateEnabling-5]
	_ = x[MmModemStateEnabled-6]
	_ = x[MmModemStateSearching-7]
	_ = x[MmModemStateRegistered-8]
	_ = x[MmModemStateDisconnecting-9]
	_ = x[MmModemStateConnecting-10]
	_ = x[MmModemStateConnected-11]
}

const _MMModemState_name = "MmModemStateFailedMmModemStateUnknownMmModemStateInitializingMmModemStateLockedMmModemStateDisabledMmModemStateDisablingMmModemStateEnablingMmModemStateEnabledMmModemStateSearchingMmModemStateRegisteredMmModemStateDisconnectingMmModemStateConnectingMmModemStateConnected"

var _MMModemState_index = [...]uint16{0, 18, 37, 61, 79, 99, 120, 140, 159, 180, 202, 227, 249, 270}

func (i MMModemState) String() string {
	i -= -1
	if i < 0 || i >= MMModemState(len(_MMModemState_index)-1) {
		return "MMModemState(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _MMModemState_name[_MMModemState_index[i]:_MMModemState_index[i+1]]
}
