// Code generated by "stringer -type=MMOmaSessionState"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmOmaSessionStateFailed - -1]
	_ = x[MmOmaSessionStateUnknown-0]
	_ = x[MmOmaSessionStateStarted-1]
	_ = x[MmOmaSessionStateRetrying-2]
	_ = x[MmOmaSessionStateConnecting-3]
	_ = x[MmOmaSessionStateConnected-4]
	_ = x[MmOmaSessionStateAuthenticated-5]
	_ = x[MmOmaSessionStateMdnDownloaded-10]
	_ = x[MmOmaSessionStateMsidDownloaded-11]
	_ = x[MmOmaSessionStatePrlDownloaded-12]
	_ = x[MmOmaSessionStateMipProfileDownloaded-13]
	_ = x[MmOmaSessionStateCompleted-20]
}

const (
	_MMOmaSessionState_name_0 = "MmOmaSessionStateFailedMmOmaSessionStateUnknownMmOmaSessionStateStartedMmOmaSessionStateRetryingMmOmaSessionStateConnectingMmOmaSessionStateConnectedMmOmaSessionStateAuthenticated"
	_MMOmaSessionState_name_1 = "MmOmaSessionStateMdnDownloadedMmOmaSessionStateMsidDownloadedMmOmaSessionStatePrlDownloadedMmOmaSessionStateMipProfileDownloaded"
	_MMOmaSessionState_name_2 = "MmOmaSessionStateCompleted"
)

var (
	_MMOmaSessionState_index_0 = [...]uint8{0, 23, 47, 71, 96, 123, 149, 179}
	_MMOmaSessionState_index_1 = [...]uint8{0, 30, 61, 91, 128}
)

func (i MMOmaSessionState) String() string {
	switch {
	case -1 <= i && i <= 5:
		i -= -1
		return _MMOmaSessionState_name_0[_MMOmaSessionState_index_0[i]:_MMOmaSessionState_index_0[i+1]]
	case 10 <= i && i <= 13:
		i -= 10
		return _MMOmaSessionState_name_1[_MMOmaSessionState_index_1[i]:_MMOmaSessionState_index_1[i+1]]
	case i == 20:
		return _MMOmaSessionState_name_2
	default:
		return "MMOmaSessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
