// Code generated by "stringer -type=MMOmaFeature"; DO NOT EDIT.

package go_modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmOmaFeatureNone-0]
	_ = x[MmOmaFeatureDeviceProvisioning-1]
	_ = x[MmOmaFeaturePrlUpdate-2]
	_ = x[MmOmaFeatureHandsFreeActivation-4]
}

const (
	_MMOmaFeature_name_0 = "MmOmaFeatureNoneMmOmaFeatureDeviceProvisioningMmOmaFeaturePrlUpdate"
	_MMOmaFeature_name_1 = "MmOmaFeatureHandsFreeActivation"
)

var (
	_MMOmaFeature_index_0 = [...]uint8{0, 16, 46, 67}
)

func (i MMOmaFeature) String() string {
	switch {
	case i <= 2:
		return _MMOmaFeature_name_0[_MMOmaFeature_index_0[i]:_MMOmaFeature_index_0[i+1]]
	case i == 4:
		return _MMOmaFeature_name_1
	default:
		return "MMOmaFeature(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
