// Code generated by "stringer -type=MMSmsState"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmSmsStateUnknown-0]
	_ = x[MmSmsStateStored-1]
	_ = x[MmSmsStateReceiving-2]
	_ = x[MmSmsStateReceived-3]
	_ = x[MmSmsStateSending-4]
	_ = x[MmSmsStateSent-5]
}

const _MMSmsState_name = "MmSmsStateUnknownMmSmsStateStoredMmSmsStateReceivingMmSmsStateReceivedMmSmsStateSendingMmSmsStateSent"

var _MMSmsState_index = [...]uint8{0, 17, 33, 52, 70, 87, 101}

func (i MMSmsState) String() string {
	if i >= MMSmsState(len(_MMSmsState_index)-1) {
		return "MMSmsState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMSmsState_name[_MMSmsState_index[i]:_MMSmsState_index[i+1]]
}
