// Code generated by "stringer -type=MMBearerType -trimprefix=MmBearerType"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmBearerTypeUnknown-0]
	_ = x[MmBearerTypeDefault-1]
	_ = x[MmBearerTypeDefaultAttach-2]
	_ = x[MmBearerTypeDedicated-3]
}

const _MMBearerType_name = "UnknownDefaultDefaultAttachDedicated"

var _MMBearerType_index = [...]uint8{0, 7, 14, 27, 36}

func (i MMBearerType) String() string {
	if i >= MMBearerType(len(_MMBearerType_index)-1) {
		return "MMBearerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMBearerType_name[_MMBearerType_index[i]:_MMBearerType_index[i+1]]
}
