// Code generated by "stringer -type=MMCallDirection -trimprefix=MmCallDirection"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmCallDirectionUnknown-0]
	_ = x[MmCallDirectionIncoming-1]
	_ = x[MmCallDirectionOutgoing-2]
}

const _MMCallDirection_name = "UnknownIncomingOutgoing"

var _MMCallDirection_index = [...]uint8{0, 7, 15, 23}

func (i MMCallDirection) String() string {
	if i >= MMCallDirection(len(_MMCallDirection_index)-1) {
		return "MMCallDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMCallDirection_name[_MMCallDirection_index[i]:_MMCallDirection_index[i+1]]
}
