// Code generated by "stringer -type=MMCallStateReason -trimprefix=MmCallStateReason"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmCallStateReasonUnknown-0]
	_ = x[MmCallStateReasonOutgoingStarted-1]
	_ = x[MmCallStateReasonIncomingNew-2]
	_ = x[MmCallStateReasonAccepted-3]
	_ = x[MmCallStateReasonTerminated-4]
	_ = x[MmCallStateReasonRefusedOrBusy-5]
	_ = x[MmCallStateReasonError-6]
	_ = x[MmCallStateReasonAudioSetupFailed-7]
	_ = x[MmCallStateReasonTransferred-8]
	_ = x[MmCallStateReasonDeflected-9]
}

const _MMCallStateReason_name = "UnknownOutgoingStartedIncomingNewAcceptedTerminatedRefusedOrBusyErrorAudioSetupFailedTransferredDeflected"

var _MMCallStateReason_index = [...]uint8{0, 7, 22, 33, 41, 51, 64, 69, 85, 96, 105}

func (i MMCallStateReason) String() string {
	if i >= MMCallStateReason(len(_MMCallStateReason_index)-1) {
		return "MMCallStateReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMCallStateReason_name[_MMCallStateReason_index[i]:_MMCallStateReason_index[i+1]]
}
