// Code generated by "stringer -type=MMCdmaActivationError -trimprefix=MmCdmaActivationError"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmCdmaActivationErrorNone-0]
	_ = x[MmCdmaActivationErrorUnknown-1]
	_ = x[MmCdmaActivationErrorRoaming-2]
	_ = x[MmCdmaActivationErrorWrongRadioInterface-3]
	_ = x[MmCdmaActivationErrorCouldNotConnect-4]
	_ = x[MmCdmaActivationErrorSecurityAuthenticationFailed-5]
	_ = x[MmCdmaActivationErrorProvisioningFailed-6]
	_ = x[MmCdmaActivationErrorNoSignal-7]
	_ = x[MmCdmaActivationErrorTimedOut-8]
	_ = x[MmCdmaActivationErrorStartFailed-9]
}

const _MMCdmaActivationError_name = "NoneUnknownRoamingWrongRadioInterfaceCouldNotConnectSecurityAuthenticationFailedProvisioningFailedNoSignalTimedOutStartFailed"

var _MMCdmaActivationError_index = [...]uint8{0, 4, 11, 18, 37, 52, 80, 98, 106, 114, 125}

func (i MMCdmaActivationError) String() string {
	if i >= MMCdmaActivationError(len(_MMCdmaActivationError_index)-1) {
		return "MMCdmaActivationError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMCdmaActivationError_name[_MMCdmaActivationError_index[i]:_MMCdmaActivationError_index[i+1]]
}
