// Code generated by "stringer -type=MMConnectionError -trimprefix=MMConnectionError"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmConnectionErrorUnknown-0]
	_ = x[MmConnectionErrorNoCarrier-1]
	_ = x[MmConnectionErrorNoDialtone-2]
	_ = x[MmConnectionErrorBusy-3]
	_ = x[MmConnectionErrorNoAnswer-4]
}

const _MMConnectionError_name = "MmConnectionErrorUnknownMmConnectionErrorNoCarrierMmConnectionErrorNoDialtoneMmConnectionErrorBusyMmConnectionErrorNoAnswer"

var _MMConnectionError_index = [...]uint8{0, 24, 50, 77, 98, 123}

func (i MMConnectionError) String() string {
	if i >= MMConnectionError(len(_MMConnectionError_index)-1) {
		return "MMConnectionError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMConnectionError_name[_MMConnectionError_index[i]:_MMConnectionError_index[i+1]]
}
