// Code generated by "stringer -type=MMCoreError -trimprefix=MMCoreError"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmCoreErrorFailed-0]
	_ = x[MmCoreErrorCancelled-1]
	_ = x[MmCoreErrorAborted-2]
	_ = x[MmCoreErrorUnsupported-3]
	_ = x[MmCoreErrorNoPlugins-4]
	_ = x[MmCoreErrorUnauthorized-5]
	_ = x[MmCoreErrorInvalidArgs-6]
	_ = x[MmCoreErrorInProgress-7]
	_ = x[MmCoreErrorWrongState-8]
	_ = x[MmCoreErrorConnected-9]
	_ = x[MmCoreErrorTooMany-10]
	_ = x[MmCoreErrorNotFound-11]
	_ = x[MmCoreErrorRetry-12]
	_ = x[MmCoreErrorExists-13]
}

const _MMCoreError_name = "MmCoreErrorFailedMmCoreErrorCancelledMmCoreErrorAbortedMmCoreErrorUnsupportedMmCoreErrorNoPluginsMmCoreErrorUnauthorizedMmCoreErrorInvalidArgsMmCoreErrorInProgressMmCoreErrorWrongStateMmCoreErrorConnectedMmCoreErrorTooManyMmCoreErrorNotFoundMmCoreErrorRetryMmCoreErrorExists"

var _MMCoreError_index = [...]uint16{0, 17, 37, 55, 77, 97, 120, 142, 163, 184, 204, 222, 241, 257, 274}

func (i MMCoreError) String() string {
	if i >= MMCoreError(len(_MMCoreError_index)-1) {
		return "MMCoreError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMCoreError_name[_MMCoreError_index[i]:_MMCoreError_index[i+1]]
}
