// Code generated by "stringer -type=MMFirmwareImageType -trimprefix=MmFirmwareImageType"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmFirmwareImageTypeUnknown-0]
	_ = x[MmFirmwareImageTypeGeneric-1]
	_ = x[MmFirmwareImageTypeGobi-2]
}

const _MMFirmwareImageType_name = "UnknownGenericGobi"

var _MMFirmwareImageType_index = [...]uint8{0, 7, 14, 18}

func (i MMFirmwareImageType) String() string {
	if i >= MMFirmwareImageType(len(_MMFirmwareImageType_index)-1) {
		return "MMFirmwareImageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMFirmwareImageType_name[_MMFirmwareImageType_index[i]:_MMFirmwareImageType_index[i+1]]
}
