// Code generated by "stringer -type=MMModem3gppUssdSessionState -trimprefix=MmModem3gppUssdSessionState"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModem3gppUssdSessionStateUnknown-0]
	_ = x[MmModem3gppUssdSessionStateIdle-1]
	_ = x[MmModem3gppUssdSessionStateActive-2]
	_ = x[MmModem3gppUssdSessionStateUserResponse-3]
}

const _MMModem3gppUssdSessionState_name = "UnknownIdleActiveUserResponse"

var _MMModem3gppUssdSessionState_index = [...]uint8{0, 7, 11, 17, 29}

func (i MMModem3gppUssdSessionState) String() string {
	if i >= MMModem3gppUssdSessionState(len(_MMModem3gppUssdSessionState_index)-1) {
		return "MMModem3gppUssdSessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModem3gppUssdSessionState_name[_MMModem3gppUssdSessionState_index[i]:_MMModem3gppUssdSessionState_index[i+1]]
}
