// Code generated by "stringer -type=MMModemFirmwareUpdateMethod -trimprefix=MmModemFirmwareUpdateMethod"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemFirmwareUpdateMethodNone-0]
	_ = x[MmModemFirmwareUpdateMethodFastboot-1]
	_ = x[MmModemFirmwareUpdateMethodQmiPdc-2]
}

const _MMModemFirmwareUpdateMethod_name = "NoneFastbootQmiPdc"

var _MMModemFirmwareUpdateMethod_index = [...]uint8{0, 4, 12, 18}

func (i MMModemFirmwareUpdateMethod) String() string {
	if i >= MMModemFirmwareUpdateMethod(len(_MMModemFirmwareUpdateMethod_index)-1) {
		return "MMModemFirmwareUpdateMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemFirmwareUpdateMethod_name[_MMModemFirmwareUpdateMethod_index[i]:_MMModemFirmwareUpdateMethod_index[i+1]]
}
