// Code generated by "stringer -type=MMModemPowerState -trimprefix=MmModemPowerState"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemPowerStateUnknown-0]
	_ = x[MmModemPowerStateOff-1]
	_ = x[MmModemPowerStateLow-2]
	_ = x[MmModemPowerStateOn-3]
}

const _MMModemPowerState_name = "UnknownOffLowOn"

var _MMModemPowerState_index = [...]uint8{0, 7, 10, 13, 15}

func (i MMModemPowerState) String() string {
	if i >= MMModemPowerState(len(_MMModemPowerState_index)-1) {
		return "MMModemPowerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemPowerState_name[_MMModemPowerState_index[i]:_MMModemPowerState_index[i+1]]
}
