// Code generated by "stringer -type=MMModemMode -trimprefix=MmModemMode"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemModeNone-0]
	_ = x[MmModemModeCs-1]
	_ = x[MmModemMode2g-2]
	_ = x[MmModemMode3g-4]
	_ = x[MmModemMode4g-8]
	_ = x[MmModemModeAny-4294967295]
}

const (
	_MMModemMode_name_0 = "NoneCs2g"
	_MMModemMode_name_1 = "3g"
	_MMModemMode_name_2 = "4g"
	_MMModemMode_name_3 = "Any"
)

var (
	_MMModemMode_index_0 = [...]uint8{0, 4, 6, 8}
)

func (i MMModemMode) String() string {
	switch {
	case i <= 2:
		return _MMModemMode_name_0[_MMModemMode_index_0[i]:_MMModemMode_index_0[i+1]]
	case i == 4:
		return _MMModemMode_name_1
	case i == 8:
		return _MMModemMode_name_2
	case i == 4294967295:
		return _MMModemMode_name_3
	default:
		return "MMModemMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
