// Code generated by "stringer -type=MMModemLocationSource -trimprefix=MmModemLocationSource"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemLocationSourceNone-0]
	_ = x[MmModemLocationSource3gppLacCi-1]
	_ = x[MmModemLocationSourceGpsRaw-2]
	_ = x[MmModemLocationSourceGpsNmea-4]
	_ = x[MmModemLocationSourceCdmaBs-8]
	_ = x[MmModemLocationSourceGpsUnmanaged-16]
	_ = x[MmModemLocationSourceAgpsMsa-32]
	_ = x[MmModemLocationSourceAgpsMsb-64]
}

const (
	_MMModemLocationSource_name_0 = "None3gppLacCiGpsRaw"
	_MMModemLocationSource_name_1 = "GpsNmea"
	_MMModemLocationSource_name_2 = "CdmaBs"
	_MMModemLocationSource_name_3 = "GpsUnmanaged"
	_MMModemLocationSource_name_4 = "AgpsMsa"
	_MMModemLocationSource_name_5 = "AgpsMsb"
)

var (
	_MMModemLocationSource_index_0 = [...]uint8{0, 4, 13, 19}
)

func (i MMModemLocationSource) String() string {
	switch {
	case i <= 2:
		return _MMModemLocationSource_name_0[_MMModemLocationSource_index_0[i]:_MMModemLocationSource_index_0[i+1]]
	case i == 4:
		return _MMModemLocationSource_name_1
	case i == 8:
		return _MMModemLocationSource_name_2
	case i == 16:
		return _MMModemLocationSource_name_3
	case i == 32:
		return _MMModemLocationSource_name_4
	case i == 64:
		return _MMModemLocationSource_name_5
	default:
		return "MMModemLocationSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
