// Code generated by "stringer -type=MMModemState -trimprefix=MmModemState"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemStateFailed - -1]
	_ = x[MmModemStateUnknown-0]
	_ = x[MmModemStateInitializing-1]
	_ = x[MmModemStateLocked-2]
	_ = x[MmModemStateDisabled-3]
	_ = x[MmModemStateDisabling-4]
	_ = x[MmModemStateEnabling-5]
	_ = x[MmModemStateEnabled-6]
	_ = x[MmModemStateSearching-7]
	_ = x[MmModemStateRegistered-8]
	_ = x[MmModemStateDisconnecting-9]
	_ = x[MmModemStateConnecting-10]
	_ = x[MmModemStateConnected-11]
}

const _MMModemState_name = "FailedUnknownInitializingLockedDisabledDisablingEnablingEnabledSearchingRegisteredDisconnectingConnectingConnected"

var _MMModemState_index = [...]uint8{0, 6, 13, 25, 31, 39, 48, 56, 63, 72, 82, 95, 105, 114}

func (i MMModemState) String() string {
	i -= -1
	if i < 0 || i >= MMModemState(len(_MMModemState_index)-1) {
		return "MMModemState(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _MMModemState_name[_MMModemState_index[i]:_MMModemState_index[i+1]]
}
