// Code generated by "stringer -type=MMModemCdmaActivationState -trimprefix=MmModemCdmaActivationState"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemCdmaActivationStateUnknown-0]
	_ = x[MmModemCdmaActivationStateNotActivated-1]
	_ = x[MmModemCdmaActivationStateActivating-2]
	_ = x[MmModemCdmaActivationStatePartiallyActivated-3]
	_ = x[MmModemCdmaActivationStateActivated-4]
}

const _MMModemCdmaActivationState_name = "UnknownNotActivatedActivatingPartiallyActivatedActivated"

var _MMModemCdmaActivationState_index = [...]uint8{0, 7, 19, 29, 47, 56}

func (i MMModemCdmaActivationState) String() string {
	if i >= MMModemCdmaActivationState(len(_MMModemCdmaActivationState_index)-1) {
		return "MMModemCdmaActivationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemCdmaActivationState_name[_MMModemCdmaActivationState_index[i]:_MMModemCdmaActivationState_index[i+1]]
}
