// Code generated by "stringer -type=MMModem3gppEpsUeModeOperation -trimprefix=MmModem3gppEpsUeModeOperation"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModem3gppEpsUeModeOperationUnknown-0]
	_ = x[MmModem3gppEpsUeModeOperationPs1-1]
	_ = x[MmModem3gppEpsUeModeOperationPs2-2]
	_ = x[MmModem3gppEpsUeModeOperationCsps1-3]
	_ = x[MmModem3gppEpsUeModeOperationCsps2-4]
}

const _MMModem3gppEpsUeModeOperation_name = "UnknownPs1Ps2Csps1Csps2"

var _MMModem3gppEpsUeModeOperation_index = [...]uint8{0, 7, 10, 13, 18, 23}

func (i MMModem3gppEpsUeModeOperation) String() string {
	if i >= MMModem3gppEpsUeModeOperation(len(_MMModem3gppEpsUeModeOperation_index)-1) {
		return "MMModem3gppEpsUeModeOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModem3gppEpsUeModeOperation_name[_MMModem3gppEpsUeModeOperation_index[i]:_MMModem3gppEpsUeModeOperation_index[i+1]]
}
