// Code generated by "stringer -type=MMModemStateFailedReason -trimprefix=MmModemStateFailedReason"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemStateFailedReasonNone-0]
	_ = x[MmModemStateFailedReasonUnknown-1]
	_ = x[MmModemStateFailedReasonSimMissing-2]
	_ = x[MmModemStateFailedReasonSimError-3]
}

const _MMModemStateFailedReason_name = "NoneUnknownSimMissingSimError"

var _MMModemStateFailedReason_index = [...]uint8{0, 4, 11, 21, 29}

func (i MMModemStateFailedReason) String() string {
	if i >= MMModemStateFailedReason(len(_MMModemStateFailedReason_index)-1) {
		return "MMModemStateFailedReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemStateFailedReason_name[_MMModemStateFailedReason_index[i]:_MMModemStateFailedReason_index[i+1]]
}
