// Code generated by "stringer -type=MMModemCdmaRmProtocol -trimprefix=MmModemCdmaRmProtocol"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemCdmaRmProtocolUnknown-0]
	_ = x[MmModemCdmaRmProtocolAsync-1]
	_ = x[MmModemCdmaRmProtocolPacketRelay-2]
	_ = x[MmModemCdmaRmProtocolPacketNetworkPpp-3]
	_ = x[MmModemCdmaRmProtocolPacketNetworkSlip-4]
	_ = x[MmModemCdmaRmProtocolStuIii-5]
}

const _MMModemCdmaRmProtocol_name = "UnknownAsyncPacketRelayPacketNetworkPppPacketNetworkSlipStuIii"

var _MMModemCdmaRmProtocol_index = [...]uint8{0, 7, 12, 23, 39, 56, 62}

func (i MMModemCdmaRmProtocol) String() string {
	if i >= MMModemCdmaRmProtocol(len(_MMModemCdmaRmProtocol_index)-1) {
		return "MMModemCdmaRmProtocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemCdmaRmProtocol_name[_MMModemCdmaRmProtocol_index[i]:_MMModemCdmaRmProtocol_index[i+1]]
}
