// Code generated by "stringer -type=MMModemLocationAssistanceDataType -trimprefix=MmModemLocationAssistanceDataType"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemLocationAssistanceDataTypeNone-0]
	_ = x[MmModemLocationAssistanceDataTypeXtra-1]
}

const _MMModemLocationAssistanceDataType_name = "NoneXtra"

var _MMModemLocationAssistanceDataType_index = [...]uint8{0, 4, 8}

func (i MMModemLocationAssistanceDataType) String() string {
	if i >= MMModemLocationAssistanceDataType(len(_MMModemLocationAssistanceDataType_index)-1) {
		return "MMModemLocationAssistanceDataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModemLocationAssistanceDataType_name[_MMModemLocationAssistanceDataType_index[i]:_MMModemLocationAssistanceDataType_index[i+1]]
}
