// Code generated by "stringer -type=MMModemPortType"; DO NOT EDIT.

package go_modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemPortTypeUnknown-1]
	_ = x[MmModemPortTypeNet-2]
	_ = x[MmModemPortTypeAt-3]
	_ = x[MmModemPortTypeQcdm-4]
	_ = x[MmModemPortTypeGps-5]
	_ = x[MmModemPortTypeQmi-6]
	_ = x[MmModemPortTypeMbim-7]
	_ = x[MmModemPortTypeAudio-8]
}

const _MMModemPortType_name = "MmModemPortTypeUnknownMmModemPortTypeNetMmModemPortTypeAtMmModemPortTypeQcdmMmModemPortTypeGpsMmModemPortTypeQmiMmModemPortTypeMbimMmModemPortTypeAudio"

var _MMModemPortType_index = [...]uint8{0, 22, 40, 57, 76, 94, 112, 131, 151}

func (i MMModemPortType) String() string {
	i -= 1
	if i >= MMModemPortType(len(_MMModemPortType_index)-1) {
		return "MMModemPortType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MMModemPortType_name[_MMModemPortType_index[i]:_MMModemPortType_index[i+1]]
}
