// Code generated by "stringer -type=MMModemAccessTechnology -trimprefix=MmModemAccessTechnology"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModemAccessTechnologyUnknown-0]
	_ = x[MmModemAccessTechnologyPots-1]
	_ = x[MmModemAccessTechnologyGsm-2]
	_ = x[MmModemAccessTechnologyGsmCompact-4]
	_ = x[MmModemAccessTechnologyGprs-8]
	_ = x[MmModemAccessTechnologyEdge-16]
	_ = x[MmModemAccessTechnologyUmts-32]
	_ = x[MmModemAccessTechnologyHsdpa-64]
	_ = x[MmModemAccessTechnologyHsupa-128]
	_ = x[MmModemAccessTechnologyHspa-256]
	_ = x[MmModemAccessTechnologyHspaPlus-512]
	_ = x[MmModemAccessTechnology1xrtt-1024]
	_ = x[MmModemAccessTechnologyEvdo0-2048]
	_ = x[MmModemAccessTechnologyEvdoa-4096]
	_ = x[MmModemAccessTechnologyEvdob-8192]
	_ = x[MmModemAccessTechnologyLte-16384]
	_ = x[MmModemAccessTechnologyAny-4294967295]
}

const _MMModemAccessTechnology_name = "UnknownPotsGsmGsmCompactGprsEdgeUmtsHsdpaHsupaHspaHspaPlus1xrttEvdo0EvdoaEvdobLteAny"

var _MMModemAccessTechnology_map = map[MMModemAccessTechnology]string{
	0:          _MMModemAccessTechnology_name[0:7],
	1:          _MMModemAccessTechnology_name[7:11],
	2:          _MMModemAccessTechnology_name[11:14],
	4:          _MMModemAccessTechnology_name[14:24],
	8:          _MMModemAccessTechnology_name[24:28],
	16:         _MMModemAccessTechnology_name[28:32],
	32:         _MMModemAccessTechnology_name[32:36],
	64:         _MMModemAccessTechnology_name[36:41],
	128:        _MMModemAccessTechnology_name[41:46],
	256:        _MMModemAccessTechnology_name[46:50],
	512:        _MMModemAccessTechnology_name[50:58],
	1024:       _MMModemAccessTechnology_name[58:63],
	2048:       _MMModemAccessTechnology_name[63:68],
	4096:       _MMModemAccessTechnology_name[68:73],
	8192:       _MMModemAccessTechnology_name[73:78],
	16384:      _MMModemAccessTechnology_name[78:81],
	4294967295: _MMModemAccessTechnology_name[81:84],
}

func (i MMModemAccessTechnology) String() string {
	if str, ok := _MMModemAccessTechnology_map[i]; ok {
		return str
	}
	return "MMModemAccessTechnology(" + strconv.FormatInt(int64(i), 10) + ")"
}
