// Code generated by "stringer -type=MMOmaSessionStateFailedReason -trimprefix=MmOmaSessionStateFailedReason"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmOmaSessionStateFailedReasonUnknown-0]
	_ = x[MmOmaSessionStateFailedReasonNetworkUnavailable-1]
	_ = x[MmOmaSessionStateFailedReasonServerUnavailable-2]
	_ = x[MmOmaSessionStateFailedReasonAuthenticationFailed-3]
	_ = x[MmOmaSessionStateFailedReasonMaxRetryExceeded-4]
	_ = x[MmOmaSessionStateFailedReasonSessionCancelled-5]
}

const _MMOmaSessionStateFailedReason_name = "UnknownNetworkUnavailableServerUnavailableAuthenticationFailedMaxRetryExceededSessionCancelled"

var _MMOmaSessionStateFailedReason_index = [...]uint8{0, 7, 25, 42, 62, 78, 94}

func (i MMOmaSessionStateFailedReason) String() string {
	if i >= MMOmaSessionStateFailedReason(len(_MMOmaSessionStateFailedReason_index)-1) {
		return "MMOmaSessionStateFailedReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMOmaSessionStateFailedReason_name[_MMOmaSessionStateFailedReason_index[i]:_MMOmaSessionStateFailedReason_index[i+1]]
}
