// Code generated by "stringer -type=MMOmaSessionType -trimprefix=MmOmaSessionType"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmOmaSessionTypeUnknown-0]
	_ = x[MmOmaSessionTypeClientInitiatedDeviceConfigure-10]
	_ = x[MmOmaSessionTypeClientInitiatedPrlUpdate-11]
	_ = x[MmOmaSessionTypeClientInitiatedHandsFreeActivation-12]
	_ = x[MmOmaSessionTypeNetworkInitiatedDeviceConfigure-20]
	_ = x[MmOmaSessionTypeNetworkInitiatedPrlUpdate-21]
	_ = x[MmOmaSessionTypeDeviceInitiatedPrlUpdate-30]
	_ = x[MmOmaSessionTypeDeviceInitiatedHandsFreeActivation-31]
}

const (
	_MMOmaSessionType_name_0 = "Unknown"
	_MMOmaSessionType_name_1 = "ClientInitiatedDeviceConfigureClientInitiatedPrlUpdateClientInitiatedHandsFreeActivation"
	_MMOmaSessionType_name_2 = "NetworkInitiatedDeviceConfigureNetworkInitiatedPrlUpdate"
	_MMOmaSessionType_name_3 = "DeviceInitiatedPrlUpdateDeviceInitiatedHandsFreeActivation"
)

var (
	_MMOmaSessionType_index_1 = [...]uint8{0, 30, 54, 88}
	_MMOmaSessionType_index_2 = [...]uint8{0, 31, 56}
	_MMOmaSessionType_index_3 = [...]uint8{0, 24, 58}
)

func (i MMOmaSessionType) String() string {
	switch {
	case i == 0:
		return _MMOmaSessionType_name_0
	case 10 <= i && i <= 12:
		i -= 10
		return _MMOmaSessionType_name_1[_MMOmaSessionType_index_1[i]:_MMOmaSessionType_index_1[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _MMOmaSessionType_name_2[_MMOmaSessionType_index_2[i]:_MMOmaSessionType_index_2[i+1]]
	case 30 <= i && i <= 31:
		i -= 30
		return _MMOmaSessionType_name_3[_MMOmaSessionType_index_3[i]:_MMOmaSessionType_index_3[i+1]]
	default:
		return "MMOmaSessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
