// Code generated by "stringer -type=MMSignalPropertyType -trimprefix=MMSignalPropertyType"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MMSignalPropertyTypeCdma-0]
	_ = x[MMSignalPropertyTypeEvdo-1]
	_ = x[MMSignalPropertyTypeGsm-2]
	_ = x[MMSignalPropertyTypeUmts-3]
	_ = x[MMSignalPropertyTypeLte-4]
}

const _MMSignalPropertyType_name = "CdmaEvdoGsmUmtsLte"

var _MMSignalPropertyType_index = [...]uint8{0, 4, 8, 11, 15, 18}

func (i MMSignalPropertyType) String() string {
	if i >= MMSignalPropertyType(len(_MMSignalPropertyType_index)-1) {
		return "MMSignalPropertyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMSignalPropertyType_name[_MMSignalPropertyType_index[i]:_MMSignalPropertyType_index[i+1]]
}
